# Inflation Data

In [7]:
import requests
import json
import prettytable
import numpy as np
import pandas as pd
import matplotlib as plot

In [5]:
headers = {'Content-type': 'application/json'}
data = json.dumps({"seriesid": ['CUUR0000SA0','SUUR0000SA0'],"startyear":"2011", "endyear":"2021"})
p = requests.post('https://api.bls.gov/publicAPI/v2/timeseries/data/', data=data, headers=headers)
json_data = json.loads(p.text)
for series in json_data['Results']['series']:
    x=prettytable.PrettyTable(["series id","year","period","value","footnotes"])
    seriesId = series['seriesID']
    for item in series['data']:
        year = item['year']
        period = item['period']
        value = item['value']
        footnotes=""
        for footnote in item['footnotes']:
            if footnote:
                footnotes = footnotes + footnote['text'] + ','
        if 'M01' <= period <= 'M12':
            x.add_row([seriesId,year,period,value,footnotes[0:-1]])
    output = open(seriesId + '.txt','w')
    output.write (x.get_string())
    output.close()

In [6]:
x

+-------------+------+--------+---------+-----------+
|  series id  | year | period |  value  | footnotes |
+-------------+------+--------+---------+-----------+
| SUUR0000SA0 | 2020 |  M12   | 146.477 |  Interim  |
| SUUR0000SA0 | 2020 |  M11   | 146.352 |  Interim  |
| SUUR0000SA0 | 2020 |  M10   | 146.461 |  Interim  |
| SUUR0000SA0 | 2020 |  M09   | 146.417 |           |
| SUUR0000SA0 | 2020 |  M08   | 146.270 |           |
| SUUR0000SA0 | 2020 |  M07   | 145.747 |           |
| SUUR0000SA0 | 2020 |  M06   | 144.847 |           |
| SUUR0000SA0 | 2020 |  M05   | 144.018 |           |
| SUUR0000SA0 | 2020 |  M04   | 144.142 |           |
| SUUR0000SA0 | 2020 |  M03   | 144.913 |           |
| SUUR0000SA0 | 2020 |  M02   | 145.193 |           |
| SUUR0000SA0 | 2020 |  M01   | 144.813 |           |
| SUUR0000SA0 | 2019 |  M12   | 144.251 |           |
| SUUR0000SA0 | 2019 |  M11   | 144.518 |           |
| SUUR0000SA0 | 2019 |  M10   | 144.629 |           |
| SUUR0000SA0 | 2019 |  M09   | 144.428 |           |
| SUUR0000SA0 | 2019 |  M08   | 144.388 |           |
| SUUR0000SA0 | 2019 |  M07   | 144.409 |           |
| SUUR0000SA0 | 2019 |  M06   | 144.243 |           |
| SUUR0000SA0 | 2019 |  M05   | 144.183 |           |
| SUUR0000SA0 | 2019 |  M04   | 143.926 |           |
| SUUR0000SA0 | 2019 |  M03   | 143.297 |           |
| SUUR0000SA0 | 2019 |  M02   | 142.571 |           |
| SUUR0000SA0 | 2019 |  M01   | 142.001 |           |
| SUUR0000SA0 | 2018 |  M12   | 141.699 |           |
| SUUR0000SA0 | 2018 |  M11   | 142.238 |           |
| SUUR0000SA0 | 2018 |  M10   | 142.700 |           |
| SUUR0000SA0 | 2018 |  M09   | 142.489 |           |
| SUUR0000SA0 | 2018 |  M08   | 142.317 |           |
| SUUR0000SA0 | 2018 |  M07   | 142.317 |           |
| SUUR0000SA0 | 2018 |  M06   | 142.349 |           |
| SUUR0000SA0 | 2018 |  M05   | 142.146 |           |
| SUUR0000SA0 | 2018 |  M04   | 141.662 |           |
| SUUR0000SA0 | 2018 |  M03   | 141.142 |           |
| SUUR0000SA0 | 2018 |  M02   | 140.805 |           |
| SUUR0000SA0 | 2018 |  M01   | 140.239 |           |
| SUUR0000SA0 | 2017 |  M12   | 139.546 |           |
| SUUR0000SA0 | 2017 |  M11   | 139.720 |           |
| SUUR0000SA0 | 2017 |  M10   | 139.782 |           |
| SUUR0000SA0 | 2017 |  M09   | 139.878 |           |
| SUUR0000SA0 | 2017 |  M08   | 139.128 |           |
| SUUR0000SA0 | 2017 |  M07   | 138.755 |           |
| SUUR0000SA0 | 2017 |  M06   | 138.989 |           |
| SUUR0000SA0 | 2017 |  M05   | 138.922 |           |
| SUUR0000SA0 | 2017 |  M04   | 138.810 |           |
| SUUR0000SA0 | 2017 |  M03   | 138.461 |           |
| SUUR0000SA0 | 2017 |  M02   | 138.403 |           |
| SUUR0000SA0 | 2017 |  M01   | 138.035 |           |
| SUUR0000SA0 | 2016 |  M12   | 137.221 |           |
| SUUR0000SA0 | 2016 |  M11   | 137.253 |           |
| SUUR0000SA0 | 2016 |  M10   | 137.536 |           |
| SUUR0000SA0 | 2016 |  M09   | 137.328 |           |
| SUUR0000SA0 | 2016 |  M08   | 137.026 |           |
| SUUR0000SA0 | 2016 |  M07   | 137.007 |           |
| SUUR0000SA0 | 2016 |  M06   | 137.329 |           |
| SUUR0000SA0 | 2016 |  M05   | 136.895 |           |
| SUUR0000SA0 | 2016 |  M04   | 136.332 |           |
| SUUR0000SA0 | 2016 |  M03   | 135.655 |           |
| SUUR0000SA0 | 2016 |  M02   | 134.953 |           |
| SUUR0000SA0 | 2016 |  M01   | 134.966 |           |
| SUUR0000SA0 | 2015 |  M12   | 134.788 |           |
| SUUR0000SA0 | 2015 |  M11   | 135.393 |           |
| SUUR0000SA0 | 2015 |  M10   | 135.735 |           |
| SUUR0000SA0 | 2015 |  M09   | 135.837 |           |
| SUUR0000SA0 | 2015 |  M08   | 136.125 |           |
| SUUR0000SA0 | 2015 |  M07   | 136.371 |           |
| SUUR0000SA0 | 2015 |  M06   | 136.391 |           |
| SUUR0000SA0 | 2015 |  M05   | 135.977 |           |
| SUUR0000SA0 | 2015 |  M04   | 135.222 |           |
| SUUR0000SA0 | 2015 |  M03   | 134.969 |           |
| SUUR0000SA0 | 2015 |  M02   | 134.053 |           |
| SUUR0000SA0 | 2015 |  M01   | 133.487 |           |
| SUUR0000SA0 | 2014 |  M12   | 134.207 |           |
| SUUR0000SA0 | 2014 |  M11   | 135.107 |           |
| SUUR0000SA0 | 2014 |  M10   | 135.891 |           |
| SUUR0000SA0 | 2014 |  M09   | 136.211 |           |
| SUUR0000SA0 | 2014 |  M08   | 136.127 |           |
| SUUR0000SA0 | 2014 |  M07   | 136.392 |           |
| SUUR0000SA0 | 2014 |  M06   | 136.433 |           |
| SUUR0000SA0 | 2014 |  M05   | 136.216 |           |
| SUUR0000SA0 | 2014 |  M04   | 135.771 |           |
| SUUR0000SA0 | 2014 |  M03   | 135.375 |           |
| SUUR0000SA0 | 2014 |  M02   | 134.542 |           |
| SUUR0000SA0 | 2014 |  M01   | 134.017 |           |
| SUUR0000SA0 | 2013 |  M12   | 133.509 |           |
| SUUR0000SA0 | 2013 |  M11   | 133.596 |           |
| SUUR0000SA0 | 2013 |  M10   | 133.876 |           |
| SUUR0000SA0 | 2013 |  M09   | 134.255 |           |
| SUUR0000SA0 | 2013 |  M08   | 134.098 |           |
| SUUR0000SA0 | 2013 |  M07   | 133.919 |           |
| SUUR0000SA0 | 2013 |  M06   | 133.900 |           |
| SUUR0000SA0 | 2013 |  M05   | 133.626 |           |
| SUUR0000SA0 | 2013 |  M04   | 133.421 |           |
| SUUR0000SA0 | 2013 |  M03   | 133.558 |           |
| SUUR0000SA0 | 2013 |  M02   | 133.204 |           |
| SUUR0000SA0 | 2013 |  M01   | 132.137 |           |
| SUUR0000SA0 | 2012 |  M12   | 131.770 |           |
| SUUR0000SA0 | 2012 |  M11   | 132.208 |           |
| SUUR0000SA0 | 2012 |  M10   | 132.892 |           |
| SUUR0000SA0 | 2012 |  M09   | 132.988 |           |
| SUUR0000SA0 | 2012 |  M08   | 132.430 |           |
| SUUR0000SA0 | 2012 |  M07   | 131.731 |           |
| SUUR0000SA0 | 2012 |  M06   | 131.956 |           |
| SUUR0000SA0 | 2012 |  M05   | 132.154 |           |
| SUUR0000SA0 | 2012 |  M04   | 132.284 |           |
| SUUR0000SA0 | 2012 |  M03   | 131.905 |           |
| SUUR0000SA0 | 2012 |  M02   | 130.953 |           |
| SUUR0000SA0 | 2012 |  M01   | 130.438 |           |
| SUUR0000SA0 | 2011 |  M12   | 129.844 |           |
| SUUR0000SA0 | 2011 |  M11   | 130.196 |           |
| SUUR0000SA0 | 2011 |  M10   | 130.373 |           |
| SUUR0000SA0 | 2011 |  M09   | 130.635 |           |
| SUUR0000SA0 | 2011 |  M08   | 130.351 |           |
| SUUR0000SA0 | 2011 |  M07   | 129.983 |           |
| SUUR0000SA0 | 2011 |  M06   | 129.846 |           |
| SUUR0000SA0 | 2011 |  M05   | 129.999 |           |
| SUUR0000SA0 | 2011 |  M04   | 129.483 |           |
| SUUR0000SA0 | 2011 |  M03   | 128.585 |           |
| SUUR0000SA0 | 2011 |  M02   | 127.363 |           |
| SUUR0000SA0 | 2011 |  M01   | 126.778 |           |
+-------------+------+--------+---------+-----------+

In [9]:
x = pd.DataFrame(x)

ValueError: DataFrame constructor not properly called!

In [11]:
plot(x.)

TypeError: 'module' object is not callable

In [12]:
value

'126.778'